default: &default
  adapter: postgresql
  host: localhost
  username: optimizeplayer
  password: 123
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: file_converter_development

test:
  <<: *default
  database: file_converter_test

production:
  <<: *default
  database: file_converter_production
