format = Format.create(name: 'images')
Extension.create(name: '.png', format: format)
Extension.create(name: '.jpg', format: format)
Extension.create(name: '.bmp', format: format)
format = Format.create(name: 'documents')
Extension.create(name: '.text', format: format)
Extension.create(name: '.doc', format: format)
Extension.create(name: '.docx', format: format)
