format = Format.create(name: 'images')
png = Extension.create(name: 'png', format: format)
jpg = Extension.create(name: 'jpeg', format: format)
bmp = Extension.create(name: 'bmp', format: format)
jpg.extension_associations.create(converted_extension: png)
jpg.extension_associations.create(converted_extension: bmp)
png.extension_associations.create(converted_extension: jpg)
png.extension_associations.create(converted_extension: bmp)
bmp.extension_associations.create(converted_extension: jpg)
bmp.extension_associations.create(converted_extension: png)

format = Format.create(name: 'documents')
txt = Extension.create(name: 'txt', format: format)
docx = Extension.create(name: 'docx', format: format)
pdf = Extension.create(name: 'pdf', format: format)
html = Extension.create(name: 'html', format: format)
txt.extension_associations.create(converted_extension: pdf)
txt.extension_associations.create(converted_extension: docx)
docx.extension_associations.create(converted_extension: pdf)
docx.extension_associations.create(converted_extension: txt)
pdf.extension_associations.create(converted_extension: txt)
pdf.extension_associations.create(converted_extension: docx)
pdf.extension_associations.create(converted_extension: png)
pdf.extension_associations.create(converted_extension: html)
png.extension_associations.create(converted_extension: pdf)

format = Format.create(name: 'videos')
mp4 = Extension.create(name: 'mp4', format: format)
avi = Extension.create(name: 'avi', format: format)
mp4.extension_associations.create(converted_extension: png)
mp4.extension_associations.create(converted_extension: avi)
avi.extension_associations.create(converted_extension: mp4)

format = Format.create(name: 'audios')
mp3 = Extension.create(name: 'mp3', format: format)
wav = Extension.create(name: 'wav', format: format)
mp3.extension_associations.create(converted_extension: wav)
wav.extension_associations.create(converted_extension: mp3)
