format = Format.create(name: 'images')
png = Extension.create(name: 'png', format: format)
jpg = Extension.create(name: 'jpeg', format: format)
bmp = Extension.create(name: 'bmp', format: format)
jpg.extension_associations.create(converted_extension: png)
jpg.extension_associations.create(converted_extension: bmp)
png.extension_associations.create(converted_extension: jpg)
png.extension_associations.create(converted_extension: bmp)
bmp.extension_associations.create(converted_extension: jpg)
bmp.extension_associations.create(converted_extension: png)
format = Format.create(name: 'documents')
txt = Extension.create(name: 'txt', format: format)
docx = Extension.create(name: 'docx', format: format)
pdf = Extension.create(name: 'pdf', format: format)
txt.extension_associations.create(converted_extension: pdf)
txt.extension_associations.create(converted_extension: docx)
docx.extension_associations.create(converted_extension: pdf)
docx.extension_associations.create(converted_extension: txt)
pdf.extension_associations.create(converted_extension: txt)
pdf.extension_associations.create(converted_extension: docx)
pdf.extension_associations.create(converted_extension: png)
png.extension_associations.create(converted_extension: pdf)
